kafka {
  bootstrap-servers = "localhost:9092"
  bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}

  topic = "transactions"
  topic = ${?KAFKA_TOPIC}

  consumer-group = "consumer"
  consumer-group = ${?KAFKA_CONSUMER_GROUP}

  producer {
    acks = "all"
    acks = ${?KAFKA_PRODUCER_ACKS}

    retries = 3
    retries = ${?KAFKA_PRODUCER_RETRIES}
  }
}

producer {
  generation-interval = 10s
  generation-interval = ${?PRODUCER_GENERATION_INTERVAL}
}

spark {
  master = "local[*]"
  master = ${?SPARK_MASTER}

  app-name = "consumer"
  app-name = ${?SPARK_APP_NAME}

  checkpoint-location = "./checkpoint"
  checkpoint-location = ${?SPARK_CHECKPOINT_LOCATION}

  rejected-transactions-path = "./output/rejected-transactions"
  rejected-transactions-path = ${?SPARK_REJECTED_TRANSACTIONS_PATH}

  transactions-log-path = "./output/transactions.log"
  transactions-log-path = ${?SPARK_TRANSACTIONS_LOG_PATH}

  trigger-interval = 60s
  trigger-interval = ${?SPARK_TRIGGER_INTERVAL}

  starting-offsets = "earliest"
  starting-offsets = ${?SPARK_STARTING_OFFSETS}

  log-level = "WARN"
  log-level = ${?SPARK_LOG_LEVEL}
}